server.port=${PORT}
server.servlet.context-path=/SpringBoot_Medical_News
spring.application.name=SpringBoot_Medical_News


spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.show-sql=true

jwt.signerKey=${SIGNERKEY}
jwt.expired=60
jwt.refreshabled=120
token.cleaner.fixedRate=7200000





cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

email.username=${USERNAME_EMAIL_SERVICE}
email.password=${PASSWORD_EMAIL_APP}